/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as BlogTagsRouteRouteImport } from './routes/blog/tags/route'
import { Route as BlogSeriesRouteRouteImport } from './routes/blog/series/route'
import { Route as BlogTagsIndexRouteImport } from './routes/blog/tags/index'
import { Route as BlogSeriesIndexRouteImport } from './routes/blog/series/index'
import { Route as BlogTagsSplatRouteImport } from './routes/blog/tags/$'
import { Route as BlogSeriesSplatRouteImport } from './routes/blog/series/$'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogTagsRouteRoute = BlogTagsRouteRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogSeriesRouteRoute = BlogSeriesRouteRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogTagsIndexRoute = BlogTagsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogTagsRouteRoute,
} as any)
const BlogSeriesIndexRoute = BlogSeriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogSeriesRouteRoute,
} as any)
const BlogTagsSplatRoute = BlogTagsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => BlogTagsRouteRoute,
} as any)
const BlogSeriesSplatRoute = BlogSeriesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => BlogSeriesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/resume': typeof ResumeRoute
  '/blog/series': typeof BlogSeriesRouteRouteWithChildren
  '/blog/tags': typeof BlogTagsRouteRouteWithChildren
  '/blog/$': typeof BlogSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/series/$': typeof BlogSeriesSplatRoute
  '/blog/tags/$': typeof BlogTagsSplatRoute
  '/blog/series/': typeof BlogSeriesIndexRoute
  '/blog/tags/': typeof BlogTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/blog/$': typeof BlogSplatRoute
  '/blog': typeof BlogIndexRoute
  '/blog/series/$': typeof BlogSeriesSplatRoute
  '/blog/tags/$': typeof BlogTagsSplatRoute
  '/blog/series': typeof BlogSeriesIndexRoute
  '/blog/tags': typeof BlogTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/resume': typeof ResumeRoute
  '/blog/series': typeof BlogSeriesRouteRouteWithChildren
  '/blog/tags': typeof BlogTagsRouteRouteWithChildren
  '/blog/$': typeof BlogSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/series/$': typeof BlogSeriesSplatRoute
  '/blog/tags/$': typeof BlogTagsSplatRoute
  '/blog/series/': typeof BlogSeriesIndexRoute
  '/blog/tags/': typeof BlogTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/resume'
    | '/blog/series'
    | '/blog/tags'
    | '/blog/$'
    | '/blog/'
    | '/blog/series/$'
    | '/blog/tags/$'
    | '/blog/series/'
    | '/blog/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/blog/$'
    | '/blog'
    | '/blog/series/$'
    | '/blog/tags/$'
    | '/blog/series'
    | '/blog/tags'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/resume'
    | '/blog/series'
    | '/blog/tags'
    | '/blog/$'
    | '/blog/'
    | '/blog/series/$'
    | '/blog/tags/$'
    | '/blog/series/'
    | '/blog/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  ResumeRoute: typeof ResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/tags': {
      id: '/blog/tags'
      path: '/tags'
      fullPath: '/blog/tags'
      preLoaderRoute: typeof BlogTagsRouteRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/series': {
      id: '/blog/series'
      path: '/series'
      fullPath: '/blog/series'
      preLoaderRoute: typeof BlogSeriesRouteRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/tags/': {
      id: '/blog/tags/'
      path: '/'
      fullPath: '/blog/tags/'
      preLoaderRoute: typeof BlogTagsIndexRouteImport
      parentRoute: typeof BlogTagsRouteRoute
    }
    '/blog/series/': {
      id: '/blog/series/'
      path: '/'
      fullPath: '/blog/series/'
      preLoaderRoute: typeof BlogSeriesIndexRouteImport
      parentRoute: typeof BlogSeriesRouteRoute
    }
    '/blog/tags/$': {
      id: '/blog/tags/$'
      path: '/$'
      fullPath: '/blog/tags/$'
      preLoaderRoute: typeof BlogTagsSplatRouteImport
      parentRoute: typeof BlogTagsRouteRoute
    }
    '/blog/series/$': {
      id: '/blog/series/$'
      path: '/$'
      fullPath: '/blog/series/$'
      preLoaderRoute: typeof BlogSeriesSplatRouteImport
      parentRoute: typeof BlogSeriesRouteRoute
    }
  }
}

interface BlogSeriesRouteRouteChildren {
  BlogSeriesSplatRoute: typeof BlogSeriesSplatRoute
  BlogSeriesIndexRoute: typeof BlogSeriesIndexRoute
}

const BlogSeriesRouteRouteChildren: BlogSeriesRouteRouteChildren = {
  BlogSeriesSplatRoute: BlogSeriesSplatRoute,
  BlogSeriesIndexRoute: BlogSeriesIndexRoute,
}

const BlogSeriesRouteRouteWithChildren = BlogSeriesRouteRoute._addFileChildren(
  BlogSeriesRouteRouteChildren,
)

interface BlogTagsRouteRouteChildren {
  BlogTagsSplatRoute: typeof BlogTagsSplatRoute
  BlogTagsIndexRoute: typeof BlogTagsIndexRoute
}

const BlogTagsRouteRouteChildren: BlogTagsRouteRouteChildren = {
  BlogTagsSplatRoute: BlogTagsSplatRoute,
  BlogTagsIndexRoute: BlogTagsIndexRoute,
}

const BlogTagsRouteRouteWithChildren = BlogTagsRouteRoute._addFileChildren(
  BlogTagsRouteRouteChildren,
)

interface BlogRouteRouteChildren {
  BlogSeriesRouteRoute: typeof BlogSeriesRouteRouteWithChildren
  BlogTagsRouteRoute: typeof BlogTagsRouteRouteWithChildren
  BlogSplatRoute: typeof BlogSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogSeriesRouteRoute: BlogSeriesRouteRouteWithChildren,
  BlogTagsRouteRoute: BlogTagsRouteRouteWithChildren,
  BlogSplatRoute: BlogSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  ResumeRoute: ResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
