/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KoIndexRouteImport } from './routes/ko/index'
import { Route as KoResumeRouteImport } from './routes/ko/resume'
import { Route as EnResumeRouteImport } from './routes/en/resume'
import { Route as KoBlogRouteRouteImport } from './routes/ko/blog/route'
import { Route as KoBlogIndexRouteImport } from './routes/ko/blog/index'
import { Route as KoBlogSplatRouteImport } from './routes/ko/blog/$'
import { Route as KoBlogTagsRouteRouteImport } from './routes/ko/blog/tags/route'
import { Route as KoBlogSeriesRouteRouteImport } from './routes/ko/blog/series/route'
import { Route as KoBlogTagsIndexRouteImport } from './routes/ko/blog/tags/index'
import { Route as KoBlogSeriesIndexRouteImport } from './routes/ko/blog/series/index'
import { Route as KoBlogTagsSplatRouteImport } from './routes/ko/blog/tags/$'
import { Route as KoBlogSeriesSplatRouteImport } from './routes/ko/blog/series/$'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/ko/',
  path: '/ko/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoResumeRoute = KoResumeRouteImport.update({
  id: '/ko/resume',
  path: '/ko/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const EnResumeRoute = EnResumeRouteImport.update({
  id: '/en/resume',
  path: '/en/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const KoBlogRouteRoute = KoBlogRouteRouteImport.update({
  id: '/ko/blog',
  path: '/ko/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const KoBlogIndexRoute = KoBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KoBlogRouteRoute,
} as any)
const KoBlogSplatRoute = KoBlogSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => KoBlogRouteRoute,
} as any)
const KoBlogTagsRouteRoute = KoBlogTagsRouteRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => KoBlogRouteRoute,
} as any)
const KoBlogSeriesRouteRoute = KoBlogSeriesRouteRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => KoBlogRouteRoute,
} as any)
const KoBlogTagsIndexRoute = KoBlogTagsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KoBlogTagsRouteRoute,
} as any)
const KoBlogSeriesIndexRoute = KoBlogSeriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KoBlogSeriesRouteRoute,
} as any)
const KoBlogTagsSplatRoute = KoBlogTagsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => KoBlogTagsRouteRoute,
} as any)
const KoBlogSeriesSplatRoute = KoBlogSeriesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => KoBlogSeriesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/ko/blog': typeof KoBlogRouteRouteWithChildren
  '/en/resume': typeof EnResumeRoute
  '/ko/resume': typeof KoResumeRoute
  '/ko': typeof KoIndexRoute
  '/ko/blog/series': typeof KoBlogSeriesRouteRouteWithChildren
  '/ko/blog/tags': typeof KoBlogTagsRouteRouteWithChildren
  '/ko/blog/$': typeof KoBlogSplatRoute
  '/ko/blog/': typeof KoBlogIndexRoute
  '/ko/blog/series/$': typeof KoBlogSeriesSplatRoute
  '/ko/blog/tags/$': typeof KoBlogTagsSplatRoute
  '/ko/blog/series/': typeof KoBlogSeriesIndexRoute
  '/ko/blog/tags/': typeof KoBlogTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/en/resume': typeof EnResumeRoute
  '/ko/resume': typeof KoResumeRoute
  '/ko': typeof KoIndexRoute
  '/ko/blog/$': typeof KoBlogSplatRoute
  '/ko/blog': typeof KoBlogIndexRoute
  '/ko/blog/series/$': typeof KoBlogSeriesSplatRoute
  '/ko/blog/tags/$': typeof KoBlogTagsSplatRoute
  '/ko/blog/series': typeof KoBlogSeriesIndexRoute
  '/ko/blog/tags': typeof KoBlogTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/ko/blog': typeof KoBlogRouteRouteWithChildren
  '/en/resume': typeof EnResumeRoute
  '/ko/resume': typeof KoResumeRoute
  '/ko/': typeof KoIndexRoute
  '/ko/blog/series': typeof KoBlogSeriesRouteRouteWithChildren
  '/ko/blog/tags': typeof KoBlogTagsRouteRouteWithChildren
  '/ko/blog/$': typeof KoBlogSplatRoute
  '/ko/blog/': typeof KoBlogIndexRoute
  '/ko/blog/series/$': typeof KoBlogSeriesSplatRoute
  '/ko/blog/tags/$': typeof KoBlogTagsSplatRoute
  '/ko/blog/series/': typeof KoBlogSeriesIndexRoute
  '/ko/blog/tags/': typeof KoBlogTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resume'
    | '/ko/blog'
    | '/en/resume'
    | '/ko/resume'
    | '/ko'
    | '/ko/blog/series'
    | '/ko/blog/tags'
    | '/ko/blog/$'
    | '/ko/blog/'
    | '/ko/blog/series/$'
    | '/ko/blog/tags/$'
    | '/ko/blog/series/'
    | '/ko/blog/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/en/resume'
    | '/ko/resume'
    | '/ko'
    | '/ko/blog/$'
    | '/ko/blog'
    | '/ko/blog/series/$'
    | '/ko/blog/tags/$'
    | '/ko/blog/series'
    | '/ko/blog/tags'
  id:
    | '__root__'
    | '/'
    | '/resume'
    | '/ko/blog'
    | '/en/resume'
    | '/ko/resume'
    | '/ko/'
    | '/ko/blog/series'
    | '/ko/blog/tags'
    | '/ko/blog/$'
    | '/ko/blog/'
    | '/ko/blog/series/$'
    | '/ko/blog/tags/$'
    | '/ko/blog/series/'
    | '/ko/blog/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeRoute: typeof ResumeRoute
  KoBlogRouteRoute: typeof KoBlogRouteRouteWithChildren
  EnResumeRoute: typeof EnResumeRoute
  KoResumeRoute: typeof KoResumeRoute
  KoIndexRoute: typeof KoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/': {
      id: '/ko/'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/resume': {
      id: '/ko/resume'
      path: '/ko/resume'
      fullPath: '/ko/resume'
      preLoaderRoute: typeof KoResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/resume': {
      id: '/en/resume'
      path: '/en/resume'
      fullPath: '/en/resume'
      preLoaderRoute: typeof EnResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/blog': {
      id: '/ko/blog'
      path: '/ko/blog'
      fullPath: '/ko/blog'
      preLoaderRoute: typeof KoBlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/blog/': {
      id: '/ko/blog/'
      path: '/'
      fullPath: '/ko/blog/'
      preLoaderRoute: typeof KoBlogIndexRouteImport
      parentRoute: typeof KoBlogRouteRoute
    }
    '/ko/blog/$': {
      id: '/ko/blog/$'
      path: '/$'
      fullPath: '/ko/blog/$'
      preLoaderRoute: typeof KoBlogSplatRouteImport
      parentRoute: typeof KoBlogRouteRoute
    }
    '/ko/blog/tags': {
      id: '/ko/blog/tags'
      path: '/tags'
      fullPath: '/ko/blog/tags'
      preLoaderRoute: typeof KoBlogTagsRouteRouteImport
      parentRoute: typeof KoBlogRouteRoute
    }
    '/ko/blog/series': {
      id: '/ko/blog/series'
      path: '/series'
      fullPath: '/ko/blog/series'
      preLoaderRoute: typeof KoBlogSeriesRouteRouteImport
      parentRoute: typeof KoBlogRouteRoute
    }
    '/ko/blog/tags/': {
      id: '/ko/blog/tags/'
      path: '/'
      fullPath: '/ko/blog/tags/'
      preLoaderRoute: typeof KoBlogTagsIndexRouteImport
      parentRoute: typeof KoBlogTagsRouteRoute
    }
    '/ko/blog/series/': {
      id: '/ko/blog/series/'
      path: '/'
      fullPath: '/ko/blog/series/'
      preLoaderRoute: typeof KoBlogSeriesIndexRouteImport
      parentRoute: typeof KoBlogSeriesRouteRoute
    }
    '/ko/blog/tags/$': {
      id: '/ko/blog/tags/$'
      path: '/$'
      fullPath: '/ko/blog/tags/$'
      preLoaderRoute: typeof KoBlogTagsSplatRouteImport
      parentRoute: typeof KoBlogTagsRouteRoute
    }
    '/ko/blog/series/$': {
      id: '/ko/blog/series/$'
      path: '/$'
      fullPath: '/ko/blog/series/$'
      preLoaderRoute: typeof KoBlogSeriesSplatRouteImport
      parentRoute: typeof KoBlogSeriesRouteRoute
    }
  }
}

interface KoBlogSeriesRouteRouteChildren {
  KoBlogSeriesSplatRoute: typeof KoBlogSeriesSplatRoute
  KoBlogSeriesIndexRoute: typeof KoBlogSeriesIndexRoute
}

const KoBlogSeriesRouteRouteChildren: KoBlogSeriesRouteRouteChildren = {
  KoBlogSeriesSplatRoute: KoBlogSeriesSplatRoute,
  KoBlogSeriesIndexRoute: KoBlogSeriesIndexRoute,
}

const KoBlogSeriesRouteRouteWithChildren =
  KoBlogSeriesRouteRoute._addFileChildren(KoBlogSeriesRouteRouteChildren)

interface KoBlogTagsRouteRouteChildren {
  KoBlogTagsSplatRoute: typeof KoBlogTagsSplatRoute
  KoBlogTagsIndexRoute: typeof KoBlogTagsIndexRoute
}

const KoBlogTagsRouteRouteChildren: KoBlogTagsRouteRouteChildren = {
  KoBlogTagsSplatRoute: KoBlogTagsSplatRoute,
  KoBlogTagsIndexRoute: KoBlogTagsIndexRoute,
}

const KoBlogTagsRouteRouteWithChildren = KoBlogTagsRouteRoute._addFileChildren(
  KoBlogTagsRouteRouteChildren,
)

interface KoBlogRouteRouteChildren {
  KoBlogSeriesRouteRoute: typeof KoBlogSeriesRouteRouteWithChildren
  KoBlogTagsRouteRoute: typeof KoBlogTagsRouteRouteWithChildren
  KoBlogSplatRoute: typeof KoBlogSplatRoute
  KoBlogIndexRoute: typeof KoBlogIndexRoute
}

const KoBlogRouteRouteChildren: KoBlogRouteRouteChildren = {
  KoBlogSeriesRouteRoute: KoBlogSeriesRouteRouteWithChildren,
  KoBlogTagsRouteRoute: KoBlogTagsRouteRouteWithChildren,
  KoBlogSplatRoute: KoBlogSplatRoute,
  KoBlogIndexRoute: KoBlogIndexRoute,
}

const KoBlogRouteRouteWithChildren = KoBlogRouteRoute._addFileChildren(
  KoBlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeRoute: ResumeRoute,
  KoBlogRouteRoute: KoBlogRouteRouteWithChildren,
  EnResumeRoute: EnResumeRoute,
  KoResumeRoute: KoResumeRoute,
  KoIndexRoute: KoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
